controller_list:
  - name: fake_panda0_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda0_joint1
      - panda0_joint2
      - panda0_joint3
      - panda0_joint4
      - panda0_joint5
      - panda0_joint6
      - panda0_joint7
  - name: fake_panda0_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda0_finger_joint1
  - name: fake_panda1_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
  - name: fake_panda1_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda1_finger_joint1
  - name: fake_panda_multi_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda0_joint1
      - panda0_joint2
      - panda0_joint3
      - panda0_joint4
      - panda0_joint5
      - panda0_joint6
      - panda0_joint7
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
initial:  # Define initial robot poses per group
  - group: panda0_arm
    pose: ready
  - group: panda0_hand
    pose: open
  - group: panda1_arm
    pose: ready
  - group: panda1_hand
    pose: open
  - group: panda_multi_arm
    pose: ready